#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚧 Running pre-commit hook: linting..."
npm run lint

if [ $? -ne 0 ]; then
  echo "❌ Lint failed. Commit aborted by pre-commit hook."
  exit 1
else
  echo "✅ Lint passed! Proceeding with commit."
fi
