#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚧 Running pre-commit hook: linting..."
npm run lint
lint_status=$?

if [ $lint_status -ne 0 ]; then
  echo "❌ Lint failed. Commit aborted by pre-commit hook."
  exit 1
fi

echo "✅ Format & Lint passed! Proceeding with commit."
